## Assessment Criteria:

The homework will be assessed based on the following criteria:
   - **Homework_2_part1 (40%)** - All questions inside this part have the same weight.
   - **Homework_2_part2 (60%)** - All questions inside this part have the same weight.
   
   
## 1.
Create a 4×5 numpy array of all True’s

In [1]:
import numpy as np
l = np.ones((4,5),dtype=bool)
l

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 2.
Extract all even numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

array([0, 2, 4, 6, 8])

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
even_arr=np.array([i for i in arr if i%2==0])
even_arr

array([0, 2, 4, 6, 8])

## 3.

Replace all even numbers in arr with 5

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

array([5, 1, 5, 3, 5, 5, 5, 7, 5, 9])

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
even_arr5=np.array([5 if i%2==0 else i for i in arr])
even_arr5

array([5, 1, 5, 3, 5, 5, 5, 7, 5, 9])

## 4.

Convert a 1D array to a 2D array with 5 rows

Input:

np.arange(10)

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
```
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
```

In [4]:
new_arr=np.arange(10)
new_arr=new_arr.reshape((5,2))
new_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 5.

Stack arrays a and b vertically

Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

```

Desired Output:

```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [5]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 6.

Get the common items between a and b

Input:
```
a = np.array([7,2,8,2,3,4,3,4,5,3])
b = np.array([7,2,10,2,4,4,9,4,9,8])
```
Desired Output:
```
array([2, 4, 7, 8])
```

In [6]:
a = np.array([7,2,8,2,3,4,3,4,5,3])
b = np.array([7,2,10,2,4,4,9,4,9,8])
c=np.intersect1d(a,b)
c

array([2, 4, 7, 8])

## 7.

Get the positions where elements of a and b match

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
Desired Output:
```
#> (array([1, 3, 5, 7])
```

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
res=np.where(a==b)
res

(array([1, 3, 5, 7], dtype=int64),)

## 8.

You are given the function `minn` that works on two scalars and finds their minimum. Create a new function called `vectorized_minn` that will use this `minn` function and will work with two numpy arrays.

Input:
```
def minn(x, y):
    """Get the minimum of two items"""
    if x <= y:
        return x
    else:
        return y
        
        
a = np.array([78, 43, 97, 21, 343, 14, 32])
b = np.array([68, 77, 36, 42, 41, 97, 32])
vectorized_minn(a, b)
```

Desired Output:

```
array([68., 43., 36., 21., 41., 14., 32.])
```

In [8]:
def minn(x, y):
    """Get the minimum of two items"""
    if x <= y:
        return x
    else:
        return y

def vectorized_minn(a,b):
    result = np.array([minn(x, y) for x, y in zip(a,b)])
    return result

    
    

a = np.array([78, 43, 97, 21, 343, 14, 32])
b = np.array([68, 77, 36, 42, 41, 97, 32])
vectorized_minn(a, b)


array([68, 43, 36, 21, 41, 14, 32])

## 9.

Swap first and second rows in the array arr:

Input:
```
arr = np.arange(15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])
       
```

Desired Output:

```
array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])
```


In [9]:
arr = np.arange(15).reshape(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
temp=arr[0].copy()
arr[0]=arr[1].copy()
arr[1]=temp
arr

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## 10.

You are given a numpy array. Set the numpy options so that when printed, only 8 of the array elements are printed.

Input:
```
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

```

Desired Output:
```
#> array([ 0,  1,  2, ..., 12, 13, 14])
```

In [11]:
a = np.arange(15)
with np.printoptions(threshold=8):
    print(a)


[ 0  1  2 ... 12 13 14]


## 11.

You are given a numpy array. Write a function `sort_arr_indexes` that will take numpy array and return the indices of the sorted elements of a given array.

Input:

```
arr = np.array([5342, 2326, 4232, 9765, 3218, 2678, 8564])
```

Output:

```
array([1, 5, 4, 2, 0, 6, 3], dtype=int64)
```


In [12]:
def sort_arr_indexes(arr):
    return np.argsort(arr)

arr = np.array([5342, 2326, 4232, 9765, 3218, 2678, 8564])
sorted_indices = sort_arr_indexes(arr)
sorted_indices


array([1, 5, 4, 2, 0, 6, 3], dtype=int64)